project_id = "kcmopdntriyepywgphfz"

[functions.create-user]
verify_jwt = false

[functions.create-agent]
verify_jwt = false

[functions.yeastar-webhook]
verify_jwt = false

[functions.textbee-webhook]
verify_jwt = false

[functions.get-sdk-sign]
verify_jwt = false